In [1]:
# imports
import pandas as pd
import numpy as np
import time

In [2]:
intakes = pd.read_csv('../sourceData/intakes.csv')

In [3]:
intakes.head()

,Animal ID,Name,DateTime,MonthYear,Found Location,Intake Type,Intake Condition,Animal Type,Sex upon Intake,Age upon Intake,Breed,Color
0,A786884,*Brock,01/03/2019 04:19:00 PM,01/03/2019 04:19:00 PM,2501 Magin Meadow Dr in Austin (TX),Stray,Normal,Dog,Neutered Male,2 years,Beagle Mix,Tricolor
1,A706918,Belle,07/05/2015 12:59:00 PM,07/05/2015 12:59:00 PM,9409 Bluegrass Dr in Austin (TX),Stray,Normal,Dog,Spayed Female,8 years,English Springer Spaniel,White/Liver
2,A724273,Runster,04/14/2016 06:43:00 PM,04/14/2016 06:43:00 PM,2818 Palomino Trail in Austin (TX),Stray,Normal,Dog,Intact Male,11 months,Basenji Mix,Sable/White
3,A665644,NaN,10/21/2013 07:59:00 AM,10/21/2013 07:59:00 AM,Austin (TX),Stray,Sick,Cat,Intact Female,4 weeks,Domestic Shorthair Mix,Calico
4,A682524,Rio,06/29/2014 10:38:00 AM,06/29/2014 10:38:00 AM,800 Grove Blvd in Austin (TX),Stray,Normal,Dog,Neutered Male,4 years,Doberman Pinsch/Australian Cattle Dog,Tan/Gray

In [4]:
intakes.columns = ['id', 'name', 'dateTime', 'monthYear', 'foundLocation',
       'intakeType', 'intakeCondition', 'animalType', 'sex',
       'age', 'breed', 'color']

In [5]:
intakes.head()

,id,name,dateTime,monthYear,foundLocation,intakeType,intakeCondition,animalType,sex,age,breed,color
0,A786884,*Brock,01/03/2019 04:19:00 PM,01/03/2019 04:19:00 PM,2501 Magin Meadow Dr in Austin (TX),Stray,Normal,Dog,Neutered Male,2 years,Beagle Mix,Tricolor
1,A706918,Belle,07/05/2015 12:59:00 PM,07/05/2015 12:59:00 PM,9409 Bluegrass Dr in Austin (TX),Stray,Normal,Dog,Spayed Female,8 years,English Springer Spaniel,White/Liver
2,A724273,Runster,04/14/2016 06:43:00 PM,04/14/2016 06:43:00 PM,2818 Palomino Trail in Austin (TX),Stray,Normal,Dog,Intact Male,11 months,Basenji Mix,Sable/White
3,A665644,NaN,10/21/2013 07:59:00 AM,10/21/2013 07:59:00 AM,Austin (TX),Stray,Sick,Cat,Intact Female,4 weeks,Domestic Shorthair Mix,Calico
4,A682524,Rio,06/29/2014 10:38:00 AM,06/29/2014 10:38:00 AM,800 Grove Blvd in Austin (TX),Stray,Normal,Dog,Neutered Male,4 years,Doberman Pinsch/Australian Cattle Dog,Tan/Gray

In [7]:
intakes['age'].unique()

array(['2 years', '8 years', '11 months', '4 weeks', '4 years', '6 years',
       '5 months', '14 years', '1 month', '2 months', '18 years',
       '4 months', '1 year', '6 months', '3 years', '4 days', '1 day',
       '5 years', '2 weeks', '15 years', '7 years', '3 weeks', '3 months',
       '12 years', '1 week', '9 months', '10 years', '10 months',
       '7 months', '9 years', '8 months', '1 weeks', '5 days', '2 days',
       '11 years', '0 years', '17 years', '3 days', '13 years', '5 weeks',
       '19 years', '6 days', '16 years', '20 years', '-1 years',
       '22 years', '23 years', '-2 years', '21 years', '-3 years',
       '25 years', '24 years'], dtype=object)

In [9]:
intakes[intakes['age'] == '-1 years']

,id,name,dateTime,monthYear,foundLocation,intakeType,intakeCondition,animalType,sex,age,breed,color
11602,A687107,Montopolis,10/04/2017 10:22:00 AM,10/04/2017 10:22:00 AM,East Riverside Drive And Montopolis Drive in A...,Stray,Normal,Dog,Neutered Male,-1 years,Rhod Ridgeback,Red/Brown
55110,A687107,Montopolis,06/19/2017 01:26:00 PM,06/19/2017 01:26:00 PM,7140 E Ben White in Austin (TX),Stray,Normal,Dog,Neutered Male,-1 years,Rhod Ridgeback,Red/Brown
74842,A753893,Chato,06/26/2015 04:30:00 PM,06/26/2015 04:30:00 PM,6709 Ponca Street in Austin (TX),Stray,Normal,Dog,Intact Male,-1 years,American Bulldog Mix,White/Brown
86154,A687107,Montopolis,02/27/2018 05:00:00 PM,02/27/2018 05:00:00 PM,400 West Parson in Manor (TX),Stray,Normal,Dog,Neutered Male,-1 years,Rhod Ridgeback,Red/Brown
113423,A757376,Gorda,10/13/2018 01:42:00 PM,10/13/2018 01:42:00 PM,Austin (TX),Public Assist,Normal,Dog,Spayed Female,-1 years,Miniature Schnauzer Mix,White
127125,A797495,Ace,06/14/2019 11:34:00 AM,06/14/2019 11:34:00 AM,6814 East Riverside Drive in Austin (TX),Stray,Normal,Dog,Neutered Male,-1 years,Cairn Terrier,Black/Tan

In [10]:
def neg_fix(row):
    if row['age'][0] == '-':
        val = row['age'][1:]
    else:
        val = row['age']
    return val

In [11]:
intakes['no_negs'] = intakes.apply(neg_fix, axis=1)

In [12]:
intakes[intakes['age'] == '-1 years']

,id,name,dateTime,monthYear,foundLocation,intakeType,intakeCondition,animalType,sex,age,breed,color,no_negs
11602,A687107,Montopolis,10/04/2017 10:22:00 AM,10/04/2017 10:22:00 AM,East Riverside Drive And Montopolis Drive in A...,Stray,Normal,Dog,Neutered Male,-1 years,Rhod Ridgeback,Red/Brown,1 years
55110,A687107,Montopolis,06/19/2017 01:26:00 PM,06/19/2017 01:26:00 PM,7140 E Ben White in Austin (TX),Stray,Normal,Dog,Neutered Male,-1 years,Rhod Ridgeback,Red/Brown,1 years
74842,A753893,Chato,06/26/2015 04:30:00 PM,06/26/2015 04:30:00 PM,6709 Ponca Street in Austin (TX),Stray,Normal,Dog,Intact Male,-1 years,American Bulldog Mix,White/Brown,1 years
86154,A687107,Montopolis,02/27/2018 05:00:00 PM,02/27/2018 05:00:00 PM,400 West Parson in Manor (TX),Stray,Normal,Dog,Neutered Male,-1 years,Rhod Ridgeback,Red/Brown,1 years
113423,A757376,Gorda,10/13/2018 01:42:00 PM,10/13/2018 01:42:00 PM,Austin (TX),Public Assist,Normal,Dog,Spayed Female,-1 years,Miniature Schnauzer Mix,White,1 years
127125,A797495,Ace,06/14/2019 11:34:00 AM,06/14/2019 11:34:00 AM,6814 East Riverside Drive in Austin (TX),Stray,Normal,Dog,Neutered Male,-1 years,Cairn Terrier,Black/Tan,1 years

In [13]:
def norm_age(row):
    # if it ends with year/years, multiply by 12 and enter into month col; enter number into year col
    if (row['no_negs'].split(' ')[1] == 'year') or (row['no_negs'].split(' ')[1] == 'years'):
        age_val = int(row['no_negs'].split(' ')[0])
        age_months = round(age_val * 12, 2)
        age_years = round(age_val, 2)
    # if it ends with month/months, enter number into month col; divide by 12 and place into year col
    elif (row['no_negs'].split(' ')[1] == 'month') or (row['no_negs'].split(' ')[1] == 'months'):
        age_val = int(row['no_negs'].split(' ')[0])
        age_months = round(age_val, 2)
        age_years = round(age_val/12, 2)
    # if it ends with week/weeks, divide by four and place into month col; leave default value in year col
    elif (row['no_negs'].split(' ')[1] == 'week') or (row['no_negs'].split(' ')[1] == 'weeks'):
        age_val = int(row['no_negs'].split(' ')[0])
        age_months = round(age_val/4, 2)
        age_years = 0
    # else (if it ends with day or days), leave default value in both cols
    else:
        age_months = 0
        age_years = 0
    return (age_months, age_years)

In [ ]:
def norm_age_in(row):
    # if it ends with year/years, multiply by 12 and enter into month col; enter number into year col
    if row['no_negs'].split(' ')[1] in ['year', 'years']:
        age_val = int(row['no_negs'].split(' ')[0])
        age_months = round(age_val * 12, 2)
        age_years = round(age_val, 2)
    # if it ends with month/months, enter number into month col; divide by 12 and place into year col
    elif row['no_negs'].split(' ')[1] in ['month', 'months']:
        age_val = int(row['no_negs'].split(' ')[0])
        age_months = round(age_val, 2)
        age_years = round(age_val/12, 2)
    # if it ends with week/weeks, divide by four and place into month col; leave default value in year col
    elif row['no_negs'].split(' ')[1] in ['week', 'weeks']:
        age_val = int(row['no_negs'].split(' ')[0])
        age_months = round(age_val/4, 2)
        age_years = 0
    # else (if it ends with day or days), leave default value in both cols
    else:
        age_months = 0
        age_years = 0
    return (age_months, age_years)

In [15]:
intakes[['age_months', 'age_years']] = intakes.apply(norm_age, axis=1, result_type='expand').T.values

In [16]:
intakes.head()

,id,name,dateTime,monthYear,foundLocation,intakeType,intakeCondition,animalType,sex,age,breed,color,no_negs,age_months,age_years
0,A786884,*Brock,01/03/2019 04:19:00 PM,01/03/2019 04:19:00 PM,2501 Magin Meadow Dr in Austin (TX),Stray,Normal,Dog,Neutered Male,2 years,Beagle Mix,Tricolor,2 years,24.0,2.00
1,A706918,Belle,07/05/2015 12:59:00 PM,07/05/2015 12:59:00 PM,9409 Bluegrass Dr in Austin (TX),Stray,Normal,Dog,Spayed Female,8 years,English Springer Spaniel,White/Liver,8 years,96.0,8.00
2,A724273,Runster,04/14/2016 06:43:00 PM,04/14/2016 06:43:00 PM,2818 Palomino Trail in Austin (TX),Stray,Normal,Dog,Intact Male,11 months,Basenji Mix,Sable/White,11 months,11.0,0.92
3,A665644,NaN,10/21/2013 07:59:00 AM,10/21/2013 07:59:00 AM,Austin (TX),Stray,Sick,Cat,Intact Female,4 weeks,Domestic Shorthair Mix,Calico,4 weeks,1.0,0.00
4,A682524,Rio,06/29/2014 10:38:00 AM,06/29/2014 10:38:00 AM,800 Grove Blvd in Austin (TX),Stray,Normal,Dog,Neutered Male,4 years,Doberman Pinsch/Australian Cattle Dog,Tan/Gray,4 years,48.0,4.00

In [18]:
import timeit

In [ ]:
t2 = timeit.timeit(
    "df.apply(myfunc2, axis=1, result_type='expand')",
    globals=dict(df=intakes, myfunc2=norm_age), number=10000)
print(round(t2, 3), 'seconds')

In [ ]:
t3 = timeit.timeit(
    "pd.DataFrame(np.row_stack(np.vectorize(myfunc3, otypes=['O'])(df['x'], df['y'])), index=df.index)",
    globals=dict(pd=pd, np=np, df=intakes, myfunc3=norm_age), number=10000)
print(round(t3, 3), 'seconds')